# Labels file for actions/github-labeler, crazy-max/ghaction-github-labeler ...
- name: ":bug: bug"
  color: "d73a4a"
  description: "Something isn't working"
- name: ":art: refactor"
  color: "ff7281"
  description: "Improve structure / format of the code."
- name: ":wrench: config"
  color: "ffc400"
  description: "build config etc"
- name: ":construction_worker: ci"
  color: "64b5f6"
  description: "continuous integration"
- name: ":books: docs"
  color: "0075ca"
  description: "Improvements or additions to documentation"
- name: ":white_check_mark: tests"
  color: "77e856"
  description: "Add or update tests"
- name: ":package: dependecies"
  color: "fdd0ae"
  description: "Update dependencies :alien:"
- name: "duplicate"
  color: "cfd8d7"
  description: "This issue or pull request already exists"
- name: "enhancement"
  color: "a22eef"
- name: "wontfix"
  color: "000000"
  description: "This will not be worked on"
