#!/bin/bash
# Generated using `code --list-extensions | xargs -L 1 echo code --install-extension`

code --install-extension alexkrechik.cucumberautocomplete
code --install-extension adrianwilczynski.switcher
code --install-extension ChakrounAnas.turbo-console-log
code --install-extension christian-kohler.npm-intellisense
code --install-extension christian-kohler.path-intellisense
code --install-extension cmstead.jsrefactor
code --install-extension codezombiech.gitignore
code --install-extension CoenraadS.bracket-pair-colorizer
code --install-extension CoenraadS.bracket-pair-colorizer-2
code --install-extension cyrilletuzi.angular-schematics
code --install-extension DavidAnson.vscode-markdownlint
code --install-extension dbaeumer.vscode-eslint
code --install-extension donjayamanne.githistory
code --install-extension DotJoshJohnson.xml
code --install-extension eamodio.gitlens
code --install-extension EditorConfig.EditorConfig
code --install-extension eg2.vscode-npm-script
code --install-extension esbenp.prettier-vscode
code --install-extension firefox-devtools.vscode-firefox-debug
code --install-extension formulahendry.auto-close-tag
code --install-extension formulahendry.auto-rename-tag
code --install-extension frasercrosbie.typescript-interface-to-builder-class
code --install-extension GitHub.vscode-pull-request-github
code --install-extension GregorBiswanger.json2ts
code --install-extension Gruntfuggly.todo-tree
code --install-extension hbenl.vscode-test-explorer
code --install-extension johnpapa.vscode-peacock
code --install-extension johnpapa.winteriscoming
code --install-extension krizzdewizz.refactorix
code --install-extension mehmetbsrn.test-generator
code --install-extension ms-vscode-remote.remote-ssh
code --install-extension ms-vscode-remote.remote-ssh-edit
code --install-extension ms-vscode-remote.remote-wsl
code --install-extension ms-vscode.typescript-javascript-grammar
code --install-extension ms-vscode.vscode-typescript-next
code --install-extension ms-vsliveshare.vsliveshare
code --install-extension msjsdiag.debugger-for-chrome
code --install-extension msjsdiag.debugger-for-edge
code --install-extension nhoizey.gremlins
code --install-extension nicoespeon.abracadabra
code --install-extension pflannery.vscode-versionlens
code --install-extension quicktype.quicktype
code --install-extension rbbit.typescript-hero
code --install-extension redhat.vscode-xml
code --install-extension redhat.vscode-yaml
code --install-extension salbert.comment-ts
code --install-extension sonarsource.sonarlint-vscode
code --install-extension steoates.autoimport
code --install-extension stevejpurves.cucumber
code --install-extension stringham.move-ts
code --install-extension xletohic.cucumber-json-formatter
code --install-extension ypresto.vscode-intelli-refactor
